shared: &shared
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  database: <%= ENV["MYSQL_DATABASE"] || 'federalregister_web' %>
  username: <%= ENV["MYSQL_USERNAME"] || 'federalregister' %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  port: <%= ENV["MYSQL_PORT_3306_TCP_PORT"] || 3306 %>
  host: '<%= ENV["MYSQL_PORT_3306_TCP_ADDR"] || '127.0.0.1' %>'
  reconnect: true
  encoding: utf8

development:
  <<: *shared

test:
  <<: *shared
  database: <%= ENV["MYSQL_DATABASE"] %>_test

staging:
  <<: *shared

production:
  <<: *shared
