version: '2'

services:
  web:
    image: kailasa-federalregister-web:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      WEB_PORT: 3000
      PASSENGER_MIN_INSTANCES: 2
      MYSQL_PORT_3306_TCP_ADDR: mysql
      REDIS_PORT_6379_TCP_ADDR: redis
      HONEYBADGER_API_KEY: ''
      ATTACHMENTS_AWS_ACCESS_KEY_ID: 'XXX'
      ATTACHMENTS_AWS_SECRET_ACCESS_KEY: 'XXX'
      AWS_BUCKET: 'bucketname'
      AWS_ENDPOINT: 'https://s3.wasabisys.com'
      FR_API_URL: 'https://fr.dev.nithyanandajnanalaya.org/api/v1'
      FR_BASE_URL: 'https://fr.dev.nithyanandajnanalaya.org'
      FR_INTERNAL_BASE_URL: 'https://www.fr.dev.nithyanandajnanalaya.org'
      RAILS_SESSION_KEY: AJR4R6UTEBktmmWeHd93EZVys6pmxnCK7rZLUdJb4gZLNe7J
      CONTAINER_PROCESS: rails
    restart: always

  mysql:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'

  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
